applications:
  - Airtable
  - Amazon_S3
  - Chrome
  - Discord
  - Dropbox
  - Excel
  - Google_Drive
  - Google_Sheets
  - Google_Storage
  - Google_Vision
  - Javascript
  - Mail
  - MongoDB
  - Slack
  - SQLite
  - Twilio
