applications:
  - Chrome
  - Compress
  - Cryptography
  - CSV
  - Datetime
  - Discord
  - Excel
  - Filesystem
  - GoogleStorage
  - Javascript
  - Mail
  - MongoDB
  - S3Storage
  - Slack
  - SQLite
  - Twilio
  - Twitter
  - REST
  - Instagram
  - Web
  - Vision
  - Process
  - System
  - SSH
